services:
  postgres:
    container_name: 'todo-list'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=todo_database'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
